--- u-boot-2013.10/Makefile	2013-10-16 11:08:12.000000000 -0600
+++ xxx/Makefile	2014-02-17 19:04:54.656874183 -0700
@@ -360,7 +360,7 @@
 else
 PLATFORM_LIBGCC := -L $(shell dirname `$(CC) $(CFLAGS) -print-libgcc-file-name`) -lgcc
 endif
-PLATFORM_LIBS += $(PLATFORM_LIBGCC)
+PLATFORM_LIBS += $(PLATFORM_LIBGCC) -lc
 export PLATFORM_LIBS
 
 # Special flags for CPP when processing the linker script.
sub