--- b/Makefile	2013-12-05 20:00:55.053569628 -0700
+++ a/Makefile	2013-12-05 20:00:34.471573906 -0700
@@ -360,7 +360,7 @@
 else
 PLATFORM_LIBGCC := -L $(shell dirname `$(CC) $(CFLAGS) -print-libgcc-file-name`) -lgcc
 endif
-PLATFORM_LIBS += $(PLATFORM_LIBGCC)
+PLATFORM_LIBS += $(PLATFORM_LIBGCC) -lc
 export PLATFORM_LIBS
 
 # Special flags for CPP when processing the linker script.
