#!/bin/sh

# PROVIDE: makeswapfile
# REQUIRE: FILESYSTEMS kld
# BEFORE: addswap
# KEYWORD: firstbootonly

# Special for BeagleBone.
#
# If disk is big enough, create a swap file.
#
# Leaving out the swap file lets us build an
# image small enough to boot and run on a 1GB SD
# card.  But if we happen to find ourselves with
# enough room, we can do better.
#
# This allows us to distribute a single image
# and have it work on essentially any size SD card.
#
# TODO: Figure out a clean way to have this run
# only on first boot.
#
# TODO: Make this configurable.
#
# TODO: Figure out where this should really be ordered.
# 

. /etc/rc.subr

name="makeswapfile"
start_cmd="makeswapfile_start"
stop_cmd=":"
rcvar="makeswapfile_enable"

makeswapfile_start ()
(
	# Default: If there is more than 7G free, add a 768M swap file.
	# Testing shows that 8G SD card is minimum for buildworld,
	# and that 768M swap is needed for buildworld on BeagleBone.
	makeswapfile_minfreeblocks=${makeswapfile_minfreeblocks:-14000000}
	makeswapfile_swapsize_mb=${makeswapfile_swapsize_mb:-768}

	freeblocks=`df -b /usr | tail -n 1 | awk '{print $4}'`
	if [ ! -e /usr/swap0 ]; then
		if [ ${freeblocks} -gt ${makeswapfile_minfreeblocks} ]; then
			echo Adding ${makeswapfile_swapsize_mb}MB swap file
			dd if=/dev/zero of=/usr/swap0 bs=1024k count=${makeswapfile_swapsize_mb}
			chmod 0600 /usr/swap0
			echo 'swapfile="/usr/swap0"' >> /etc/rc.conf
		else
			touch /usr/swap0
		fi
	fi
)

load_rc_config ${name}
run_rc_command "$1"
