#!/bin/sh

# PROVIDE: autosize
# BEFORE: sysctl
# KEYWORD: firstbootonly

# Special for BeagleBone.
#
# Automatically grow mmcsd0s2a to fill the
# entire SD card.
#
# This allows us to distribute a single image
# and have it work on essentially any size SD card.
#
# TODO: Figure out where this should really be ordered.
# I suspect it should go just after fsck but before mountcritlocal
# but it's hard to tell for sure because of the bug described
# below.
# 

. /etc/rc.subr

name="growfs"
start_cmd="growfs_start"
stop_cmd=":"
rcvar="growfs_enable"

growfs_start ()
{
    echo "Enlarging root partition"
    gpart resize -i 2 mmcsd0
    gpart commit mmcsd0s2
    gpart resize -i 1 mmcsd0s2
    growfs -y /dev/mmcsd0s2a
}

load_rc_config $name
run_rc_command "$1"
