name: i386 Image Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 600
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      id: build
      uses: cross-platform-actions/action@v0.24.0
      with:
        operating_system: freebsd
        version: '14.1'
        run: |
          /usr/local/bin/bash ci/ci_i386.sh
