name: RPI Image Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      id: build
      uses: vmactions/freebsd-vm@v1.0.7
      with:
        usesh: true
        release: "14.0"
        run: |
          pkg install -y git 
          echo "cloning source from https://github.com/freebsd/freebsd-src.git"
          git clone https://github.com/freebsd/freebsd-src.git -b stable/13 /usr/src 
          echo "building config/config_rpi.sh"
          sh crochet.sh -c config/config_rpi.sh -u

