name: RPI Image Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
    env:
      SOURCE_URL: "https://github.com/freebsd/freebsd-src.git"
      BRANCH: "stable/13"
      PLATFORM_SCRIPT: "ci/configs/config_rpi.sh"
      PACKAGES: "git python3 u-boot-rpi"
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      id: build
      uses: vmactions/freebsd-vm@v1.0.8
      with:
        envs: 'SOURCE_URL BRANCH PLATFORM_SCRIPT PACKAGES'
        usesh: true
        release: "14.0"
        prepare: |
          pkg install -y $PACKAGES
        run: |
          echo "cloning source branch $BRANCH from $SOURCE_URL"
          git clone $SOURCE_URL -b $BRANCH /usr/src 
          echo "building $PLATFORM_SCRIPT"
          sh crochet.sh -c $PLATFORM_SCRIPT -u -v