name: RPI Image Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOURCE_URL: "https://github.com/freebsd/freebsd-src.git"
      BRANCH: "stable/13"
      PLATFORM_SCRIPT: "configs/config_rpi.sh"
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      id: build
      uses: vmactions/freebsd-vm@v1.0.7
      with:
        envs: 'SOURCE_URL BRANCH PLATFORM_SCRIPT'
        usesh: true
        release: "14.0"
        run: |
          pkg install -y git 
          echo "cloning source from https://github.com/freebsd/freebsd-src.git"
          git clone https://github.com/freebsd/freebsd-src.git -b stable/13 /usr/src 
          echo "building configs/config_rpi.sh"
          sh crochet.sh -c configs/config_rpi.sh -u

