name: i386 Image Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
    env:
      SOURCE_URL: "https://github.com/freebsd/freebsd-src.git"
      BRANCH: "stable/13"
      PLATFORM_SCRIPT: "configs/config_i386.sh"
      PACKAGES: "git"
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      id: build
      uses: cross-platform-actions/action@v0.24.0
      with:
        operating_system: freebsd
        version: '14.0'
        environment_variables: 'SOURCE_URL BRANCH PLATFORM_SCRIPT PACKAGES'
        run: |
          sudo pkg install -y $PACKAGES
          echo "cloning source branch $BRANCH from $SOURCE_URL"
          sudo git config --global http.version HTTP/1.1
          rm -rf /usr/src
          sudo git clone $SOURCE_URL -b $BRANCH /usr/src 
          echo "building $PLATFORM_SCRIPT"
          sudo sh crochet.sh -c $PLATFORM_SCRIPT -u -v