name: i386 Image Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  PLATFORM_CONFIG: 'config/config_i386.sh'
  SOURCE_URL: 'https://github.com/freebsd/freebsd-src.git'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      id: build
      uses: vmactions/freebsd-vm@v1.0.7
      with:
        usesh: true
        release: "14.0"
        run: |
          pkg install -y git 
          echo "checking out source from $SOURCE_URL"
          git clone $SOURCE_URL /usr/src 
          echo "building $PLATFORM_CONFIG"
          sh crochet.sh -c $PLATFORM_CONFIG -u
