name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: CI 14.2
    env:
      BRANCH : releng/14.2
      CONFIG: ci/configs/config_i386.sh
    steps:
    - uses: actions/checkout@v4
    - name: CI
      id: ci
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'BRANCH CONFIG'
        usesh: true
        prepare: |
          pkg install -y sudo

        run: |
          pwd
          sudo pkg install -y git
          sudo git clone -b releng/14.2 https://git.freebsd.org/src.git /usr/src
          ls -lat /usr/src
          sh crochet.sh -c ci/configs/config_i386.sh
