name: CI

on: [push]

env:
  BRANCH: releng/14.2

jobs:
  test:
    runs-on: ubuntu-latest
    name: CI 14.2
    steps:
    - uses: actions/checkout@v4
    - name: CI
      id: ci
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y sudo

        run: |
          pwd
          sudo pkg install -y git
          sudo git clone -b $BRANCH https://git.freebsd.org/src.git /usr/src
          ls -lat /usr/src


