name: Image Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_i386:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      id: build
      uses: vmactions/freebsd-vm@v1.0.7
      with:
        usesh: true
        run: |
          pkg install -y subversion
          svn co https://svn.freebsd.org/base/head /usr/src
          sh crochet.sh -c configs/config_i386.sh -u


