#!/bin/sh

# PROVIDE: swapfile_create
# REQUIRES: mountlate
# BEFORE: swaplate
# KEYWORD: firstboot

# Create a swap file.

. /etc/rc.subr

name="swapfile_create"
start_cmd="swapfile_create_start"
stop_cmd=":"
rcvar="swapfile_create_enable"

swapfile_create_start ()
{
    swapfile_create_file=${swapfile_create_file:-/swapfile0}
    swapfile_create_size=${swapfile_create_size:-512}

    echo "Preallocating ${swapfile_create_size} MiB for swap file ${swapfile_create_file} ..."
    dd if=/dev/zero of=${swapfile_create_file} count=${swapfile_create_size} bs=1024k
    chmod 0600 "${swapfile_create_file}"

    echo "md none swap sw,late,file=${swapfile_create_file} 0 0" >> /etc/fstab
}

load_rc_config $name
run_rc_command "$1"
